### ISSUE TITLE
Rename and redefine filer variable

### ISSUE THREAD

**Issue by martinholmer** [PSLmodels/taxdata#288]
This enhancement request stems from the discussion in [Tax-Calculator issue 2099](https://github.com/open-source-economics/Tax-Calculator/issues/2099).  That discussion revealed that the `filer` variable is confusing even to advanced users of Tax-Calculator.

I suggest the following two changes:

1. The `filer` variable be renamed `data_source` in both the `puf.csv` and `cps.csv` files.

2. The `data_source` variable be defined so that records whose primary source is the IRS-SOI PUF have a `data_source` value of one (1) and that records whose primary source is the CPS have a `data_source` value of zero (0).

Notice change 2 implies that all the records in the `cps.csv` file will have a `data_source` value of zero.
My understanding is that change 2 will not affect any `data_source` values in the `puf.csv` file.

Until these enhancements can be made available for both input data files, I'm going to drop the `filer` variable from the list of USABLE_READ_VARS in Tax-Calculator.  When we have `puf.csv` and `cps.csv` files with the `data_source` variable, we can add `data_source` to the list of USABLE_READ_VARS.

**Comment by MattHJensen** [comment]
This all makes sense to me, and +1 for the `data_source` name.

**Comment by MattHJensen** [comment]
Actually, I just looked at this more closely, and I'd like to ask a clarifying question.

In my memory, `filer` referred to whether the tax unit filed income taxes in the base year. If the unit was a `filer`, then, during the construction of the puf.csv file, that taxpayer's information would have come from the IRS-SOI PUF. If the unit hadn't filed, the IRS wouldn't have their information, and we had to create their records from the CPS -- again, during the construction of puf.csv. So `filer` referred to wether the unit filer in the data's base year, but not whether the tax unit filed in any given year. 

@martinholmer, is this also your understanding of the history of `filer`?

**Comment by andersonfrailey** [comment]
@MattHJensen, your understanding of the `filer` variable is correct. That said, I do think that this definition of `filer` can be confusing especially when comparing reforms. In my opinion, the name `filer` implies that you can use it as a proxy for whether or not a unit filed in any given year and that it would change accordingly under various tax policies that change filing thresholds.

I'd be in favor of changing the current `filer` variable to something like what @martinholmer suggested  so that it only represents the data source that record was constructed from. Then we could add new logic to taxcalc that determines if a unit would be required to file under a given tax regime and assigns a value to the `filer` variable accordingly.

**Comment by MaxGhenis** [comment]
How should `filer` in the CPS file be interpreted?

```
cps = pd.read_csv('https://github.com/open-source-economics/taxdata/raw/master/cps_data/cps.csv.gz')
cps.groupby('filer').size()
# filer
# 0     19026
# 1    437439
# dtype: int64
```

**Comment by andersonfrailey** [comment]
@MaxGhenis in the CPS `filer` represents whether we flagged the unit as a filer using the 2014 standards.

**Comment by martinholmer** [comment]
@andersonfrailey,  What's the schedule for renaming and redefining the "filer" variable as decided on two months ago in taxdata issue #288?

It doesn't make sense to me to issue a new Tax-Calculator release until we get this fixed.  Users are tired of seeing this message:
```
Your data include the following unused variables that will be ignored:
  filer
```

**Comment by andersonfrailey** [comment]
@martinholmer, sorry, I hadn't realized that we had all settled on the rename. I'll take care of it this afternoon.

For clarity, I'm going to rename `filer` in the PUF to `data_source` where 1 means the PUF and 0 means the CPS. I'm also going to drop it completely from the CPS because all data comes from the CPS.

**Comment by martinholmer** [comment]
@andersonfrailey said in taxdata issue #288:
> For clarity, I'm going to rename filer in the PUF to `data_source` where 1 means the PUF and 0 means the CPS. I'm also going to drop it completely from the CPS because all data comes from the CPS.

OK.  I guess `data_source` will be like `a_lineno` and `ffpos` only the reverse: available in `puf.csv` but not in `cps.csv.gz`.

**Comment by andersonfrailey** [comment]
With the merge of PR #296 this issue has been resolved.
