### ISSUE TITLE
Add count of children under age 6

### ISSUE THREAD

**Issue by MaxGhenis** [PSLmodels/taxdata#311]
Two major tax credit bills split out children under age 6:
* [American Family Act](https://www.vox.com/future-perfect/2019/3/6/18249290/child-poverty-american-family-act-sherrod-brown-michael-bennet) (Bennet-Brown child allowance)
* [Working Families Tax Relief Act](https://www.vox.com/future-perfect/2019/4/10/18302183/tax-cut-democrats-earned-income-tax-credit-child-allowance)

Currently the `nu05` field and `_CTC_c_under5_bonus` parameter threshold at age 5, so it'd be helpful to have parallel versions of these thresholded at age 6.

**Comment by martinholmer** [comment]
Why not **replace** `nu05` with `nu06`?  The only place in Tax-Calculator code that `nu05` is used is in the `taxcalc/reforms/Clinton2016.json` file.

@MaxGhenis @andersonfrailey @MattHJensen

**Comment by MaxGhenis** [comment]
SGTM

**Comment by andersonfrailey** [comment]
I'm also on board with @martinholmer's suggestion. I can get that done for the PUF this week. However we still can't run the SAS scripts to recreate the CPS file. I have an idea to use the record identification variables we've left on the CPS file to link it with the raw CPS files to work out counting variables like this would be, but that'll take a little more time to develop and test.

**Comment by martinholmer** [comment]
@andersonfrailey said 13 days ago in taxdata issue #311:
> I'm also on board with @martinholmer's suggestion. I can get that done for the PUF this week. However we still can't run the SAS scripts to recreate the CPS file. I have an idea to use the record identification variables we've left on the CPS file to link it with the raw CPS files to work out counting variables like this would be, but that'll take a little more time to develop and test.

What's the schedule for getting this done?  Tax-Calculator users are waiting for this enhancement as you can see from the discussion of [Tax-Calculator issue 2294](https://github.com/PSLmodels/Tax-Calculator/issues/2294).

@MattHJensen

**Comment by andersonfrailey** [comment]
@martinholmer, I could get a new PUF out with the change from `nu05` to `nu06` this week. However, there are a few things to consider with making the change in the CPS. As I mentioned in the last Tax-Calculator maintainers meeting, I want to work on creating a new CPS file that is built with Python scripts so that we're no longer constrained by the SAS code we currently use. If we wait to release a new CPS file until that's ready, it will be at least a few weeks.

Alternatively, I could create a temporary solution that will count up the people under 6 in each family/household in the original CPS files (before we process them into tax units) and use the identification variables that we left in CPS.csv to merge them on. This might not be perfect, but it would be a decent stop-gap solution while I work on making the new CPS and I could get it done by the end of this week. What are you thoughts on this option?

**Comment by martinholmer** [comment]
@andersonfrailey said in issue #311:
> I could get a new PUF out with the change from nu05 to nu06 this week. However, there are a few things to consider with making the change in the CPS. As I mentioned in the last Tax-Calculator maintainers meeting, I want to work on creating a new CPS file that is built with Python scripts so that we're no longer constrained by the SAS code we currently use. If we wait to release a new CPS file until that's ready, it will be at least a few weeks.
>
> Alternatively, I could create a temporary solution that will count up the people under 6 in each family/household in the original CPS files (before we process them into tax units) and use the identification variables that we left in CPS.csv to merge them on. This might not be perfect, but it would be a decent stop-gap solution while I work on making the new CPS and I could get it done by the end of this week. What are you thoughts on this option?

My view is that our projects are an exercise in "continuous improvement," and therefore, the second (two-step) option is the preferable **of the two you mention**.   But clearly, the best option is to come to terms with the fact that we are still not free-of-SAS, and so the Policy Simulation Library needs to get a SAS license.  What's the matter with that option?

@MattHJensen

**Comment by martinholmer** [comment]
@andersonfrailey and @MattHJensen,  If the Policy Simulation Library is too poor to purchase a SAS license, then why not adapt the script @evtedeschi3 used to compute from the CPS public-use file the child age count variables used as input into Tax-Calculator?   Here is the link to that script (which is free to execute because the R distribution is completely free):
https://github.com/evtedeschi3/tcpoverty/blob/master/tcpov2a_make_taxsim27.R

**Comment by andersonfrailey** [comment]
@martinholmer I'll look into the output of @evtedeschi3's code today and see how we can work with it in taxdata.

**Comment by Thirdhuman** [comment]
Having personally replicated Ernie's calculations, the biggest barrier is that the TAXSIM27 variables cannot function if a "under 6" variable is preserved due to the required shape of the TAXSIM file.  
Ernie's distributional statistics are calculated through merging tax-calc's output back onto the original CPS extract afterwards.

I've been hoping an updated tax-calc release might be forthcoming with the nu6 variable, but the statistics can be adjusted after the fact with some tweaking.

**Comment by MattHJensen** [comment]
I was just reviewing Tax-Calculator issues and saw that https://github.com/PSLmodels/Tax-Calculator/issues/2294 depends on this issue, #311. 

@andersonfrailey, would you mind letting me know the status of this issue when you have an opportunity?

**Comment by andersonfrailey** [comment]
@MattHJensen sorry this has slipped away from me. We still have the issue of being unable to run the SAS code. What I could do is create supplement the final prep Python script to use the household and family identification information in the CPS to map back to the original CPS files, count up the number of children under five in each household, and then add that as a new variable to the CPS. I think that this could be done fairly quickly.

**Comment by MattHJensen** [comment]
I just thought to add that users of both the puf.csv file and the forthcoming synthetic version would benefit from the addition of nu06 to puf.csv as a first step, even if it is a longer-term project to add it to the cps.csv file.

**Comment by MaxGhenis** [comment]
I thought adding it to cps.csv was a prerequisite for adding it to PUF files, since it provides the ground data to impute?

**Comment by andersonfrailey** [comment]
@MattHJensen I should be able to get that done this weekend. I'll have a PR up for review as soon as I can.

@MaxGhenis adding it to cps.csv is not a requirement for adding it to the PUF since we do all of the work on the 2016 CPS file that we use to match with the PUF separately from how we create the cps.csv file. Everything we do for creating puf.csv can be found in the puf_data directory.

**Comment by MattHJensen** [comment]
> adding it to cps.csv is not a requirement for adding it to the PUF since we do all of the work on the 2016 CPS file that we use to match with the PUF separately from how we create the cps.csv file. Everything we do for creating puf.csv can be found in the puf_data directory.

As a side note to this discussion, this just reminds me that imputations of the benefits information from the C-TAM augmented `cps.csv` to `puf.csv` would be helpful: It is easier to produce new versions of `puf.csv` and it is also, generally, of higher quality than `cps.csv. If anyone ever has ideas for those imputations or is interested in working on them, I'd love to talk about it sometime.

**Comment by andersonfrailey** [comment]
Taken care of with #329 and #314. Closing.
